import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import Navbar from "@/components/Navbar";
import { toast, Toaster } from 'react-hot-toast'
import NextAuthProviderWrapper from "@/utlis/providersWrapper/nextAuthProviderWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { session, ...params } }: Readonly<{
  children: React.ReactNode, params: any
}>) {

  return (
    // <NextAuthProviderWrapper>
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          <Navbar />
          {children}
        </body>
      </html>
    </SessionProvider>
    // </NextAuthProviderWrapper>
  );
}
