import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from 'react-hot-toast'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default async function RootLayout({ children, params: { session, ...params } }: Readonly<{
//   children: React.ReactNode, params: any
// }>) {
export default async function RootLayout({ children }: Readonly<{
  children: React.ReactNode,
}>) {

  return (


    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <Navbar />
        {children}
      </body>
    </html>


  );
}
